<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meu Site Legal</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #333;
            color: #fff;
            padding: 20px;
            text-align: center;
        }

        .container {
            width: 80%;
            margin: 20px auto;
        }

        h1 {
            color: #333;
        }

        p {
            color: #666;
            line-height: 1.6;
        }

        footer {
            background-color: #333;
            color: #fff;
            padding: 10px 0;
            text-align: center;
            position: fixed;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>
    <header>
        <h1>Bem-vindo ao Meu Site Legal</h1>
    </header>

    <div class="container">
        <p>Este é um exemplo simples de um site utilizando HTML e CSS.</p>
        <p>Sinta-se à vontade para adicionar mais conteúdo e estilo conforme desejar!</p>
    </div>

    <footer>
        <p>&copy; 2024 Meu Site Legal</p>
    </footer>
</body>
</html>
